# Simple workflow for deploying static content to GitHub Pages
name: GitHub Actions

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ main ]
  # Runs on pull requests based on the default branch
  pull_request:
    branches: [ main ]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run dev server in background
        run: pnpm start:dev &
      - name: Run tests
        run: pnpm test
      - name: Run e2e tests
        run: pnpm test:e2e
